// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"coupon-service/app/api"
	"coupon-service/config"
	"coupon-service/controllers"
	"coupon-service/domains"
	"coupon-service/domains/repositories"
	"coupon-service/domains/services"
	"coupon-service/infrastructure/auth"
	"coupon-service/infrastructure/persistence"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() *api.APIContainer {
	appConfig := config.NewAppConfig()
	engineConfig := config.NewEngineConfig(appConfig)
	googleAuthConfig := config.NewGoogleAuthConfig(appConfig)
	googleOAuth := auth.NewGoogleOAuthClient(googleAuthConfig)
	authMiddleware := auth.NewAuthMiddleware(googleOAuth)
	healthCheckService := services.NewHealthCheckService()
	healthCheckController := controllers.NewHealthCheckController(healthCheckService)
	dbConfig := config.NewDBConfig(appConfig)
	db := persistence.NewDbConn(dbConfig)
	boardUserRepository := repositories.NewBoardUserRepository(db)
	boardUserService := services.NewBoardUserService(boardUserRepository, googleOAuth)
	boardUserController := controllers.NewBoardUserController(boardUserService)
	boardRepository := repositories.NewBoardRepository(db)
	boardMemberRepository := repositories.NewBoardMemberRepository(db)
	boardService := services.NewBoardService(boardRepository, boardMemberRepository)
	boardController := controllers.NewBoardController(boardService, boardUserService)
	couponRepository := repositories.NewCouponRepository(db)
	couponService := services.NewCouponService(couponRepository)
	couponController := controllers.NewCouponController(couponService, boardUserService)
	controllerContainer := controllers.NewRoute(authMiddleware, healthCheckController, boardUserController, boardController, couponController)
	apiContainer := api.NewAPIContainer(engineConfig, controllerContainer)
	return apiContainer
}

// wire.go:

var BindingSet = wire.NewSet(auth.AuthProvider, api.APIProvider, config.ConfigProvider, persistence.PersistenceProvider, domains.ServiceProvider, controllers.ControllerProvider)
